### ISSUE TITLE
Emoji organizer

### ISSUE THREAD

**Issue by resucutie** [vizality-community/suggestions#3]
# Description
You can organize your favorite emojis into lists. Like in the photo
![image](https://user-images.githubusercontent.com/27961224/88239073-b5a70900-cc59-11ea-952d-7166d704700c.png)

### Expected behavior
Well it'll be like as showed in the photo. You can create lists, rename them and set a color to the list. You can also change the position of the servers if you want. You can set group of emojis (useful for emojis like this: :owo1: :owo2: :owo3:). And you can change the order of it. In Discord, emojis go to Z to A. With this plugin you can change the order to A-Z.

### Additional context
Group of emojis:
![image](https://user-images.githubusercontent.com/27961224/88239358-978dd880-cc5a-11ea-80f7-addc5ff21d4a.png)
###### Blue: Group of emojis

----

 - [x] I have checked to make sure a similar request has not already been proposed
 - [x] I have checked to made sure this request complies with Vizality's [guidelines](https://github.com/vizality/vizality-community/blob/master/GUIDELINES.md)

**Comment by dperolio** [comment]
I'm not sure it will be possible to provide A-Z sorting, due to issues like lazy loading, but it may be. Going along with this, I think it would be nice if users could resize the popout vertically like they can horizontally. This would require figuring out how to get by the lazy loading as well though. Being able to add emojis to Favorites is definitely good. The groups could probably be done, but it seems like it would make it much harder and be a bit overkill to me, but if someone wants to pick it up, go for it.

Another excellent feature for this I think would adding in the ability to make the emoji responsive, growing and shrinking depending upon the size of the popout, as well as the ability to change how many emoji appear per row:

![](https://i.imgur.com/qrETE2r.gif)

 These are both sort of doable with just CSS, but then we run into the dreaded lazy loading. Lazy loading stumps progress yet again.

**Comment by dperolio** [comment]
It seems Discord has or is in the process of adding the feature of favoriting emojis, so that's a big one, but I'm still going to leave this open as there are some other ideas here.

**Comment by adntaha** [comment]
> It seems Discord has or is in the process of adding the feature of favoriting emojis, so that's a big one, but I'm still going to leave this open as there are some other ideas here.

It’s already on Canary, you can [check the data-mining repository](https://github.com/DJScias/Discord-Datamining/commit/b9576a387f9db884fc51374f33d86d7aedd289cd#commitcomment-43602978)

**Comment by dperolio** [comment]
> > It seems Discord has or is in the process of adding the feature of favoriting emojis, so that's a big one, but I'm still going to leave this open as there are some other ideas here.
> 
> It’s already on Canary, you can [check the data-mining repository](https://github.com/DJScias/Discord-Datamining/commit/b9576a387f9db884fc51374f33d86d7aedd289cd#commitcomment-43602978)

Yup, that's why I phrased it as `has or is in the process of adding`, because it's not on Stable yet.

**Comment by resucutie** [comment]
well, organizing in lists (not only favorite emojis) and making folders isn't available for now and i don't see discord making this feature a thing.

**Comment by adntaha** [comment]
> well, organizing in lists (not only favorite emojis) and making folders isn't available for now and i don't see discord making this feature a thing.

Could be called `BetterEmotes`. idk

**Comment by NotExactlyMeButMeh** [comment]
I wouldn't call it that, unless it's adding more than just folders for emotes into the mix. If it were to add emoji tagging + searching by tag(s) as well as other things such as an inbuilt scrollable autocomplete function, then I think it would be deserving of such a name.

**Comment by resucutie** [comment]
I've decided to close since I am no longer interested with Vizality (and idk about the state of the project). If you're still up to reopen it, go ahead
